# FROM amd64/alpine:3.17
FROM amd64/alpine:3.20
WORKDIR /

# set variables and locales
ENV \
    LANG="C.UTF-8"

# Add tagged repos as well as the edge repo so that we can selectively install edge packages
# RUN echo "@main http://dl-cdn.alpinelinux.org/alpine/v3.17/main" >> /etc/apk/repositories && \
RUN echo "@main http://dl-cdn.alpinelinux.org/alpine/v3.20/main" >> /etc/apk/repositories && \
    # echo "@community http://dl-cdn.alpinelinux.org/alpine/v3.17/community" >> /etc/apk/repositories && \
    echo "@community http://dl-cdn.alpinelinux.org/alpine/v3.20/community" >> /etc/apk/repositories && \
    echo "@edge http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories

# install packages
RUN apk add --no-cache \
    ca-certificates \
    curl \
    git \
    python3 \
    py3-pip \
    py3-mysqlclient \
    bash \
    && python3 -m ensurepip \
    && pip3 install --no-cache --upgrade pip setuptools wheel

ENV PYTHONPATH /usr/lib/python3/dist-packages

# create and activate a virtual environment
RUN python3 -m venv /opt/venv

# Ensure scripts inside the venv are runnable
ENV PATH="/opt/venv/bin:$PATH"

#RUN ln -sf python3 /usr/bin/python
# RUN python3 -m ensurepip --upgrade
# RUN pip3 install --no-cache --upgrade pip setuptools
RUN pip3 install --no-cache --upgrade \
    # wheel==0.38.4 \
    # wheel==0.45.1 \
    # python-can==4.2.0 \
    python-can==4.6.1 \
    # influxdb==5.3.1 \
    influxdb==5.3.2 \
    # serial==0.0.97 \
    pyserial \
    # paho-mqtt==1.6.1 \
    paho-mqtt==2.1.0 \
    # pika==1.3.1 \
    pika==1.3.2 \
    # requests==2.28.1 \
    requests==2.32.5 \
    # urllib3==1.26.13
    urllib3==2.5.0

# install pyHPSU
RUN cd /opt \
    && git clone --single-branch --branch MQTT-Session-Fix https://github.com/Petrus79/pyHPSUmqtt.git pyHPSU\
    # && git clone https://github.com/Petrus79/pyHPSUmqtt.git pyHPSU\
    && cd /opt/pyHPSU \
    && chmod +x install.sh \
    && sh install.sh

# expose volume
VOLUME /etc/pyHPSU

COPY entrypoint.sh /
RUN chmod +x entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

























