FROM arm32v7/alpine:3.20

# build ARM on AMD64
# COPY qemu-arm-static /usr/bin

# set variables and locales
ENV \
    LANG="C.UTF-8"

# Add tagged repos as well as the edge repo so that we can selectively install edge packages
RUN echo "@main http://dl-cdn.alpinelinux.org/alpine/v3.20/main" >> /etc/apk/repositories && \
    echo "@community http://dl-cdn.alpinelinux.org/alpine/v3.20/community" >> /etc/apk/repositories && \
    echo "@edge http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories

# install packages
# RUN apk add --no-cache \
RUN apk update && apk add --no-cache \
    ca-certificates \
    curl \
    git \
    build-base \
    python3 \
    # python3-dev \
    py3-pip \
    py3-mysqlclient \
    bash

# Create a Python virtual environment at /opt/venv
RUN python3 -m venv /opt/venv

# Create and activate virtual environment, then upgrade pip and install packages inside it
RUN /opt/venv/bin/pip install --upgrade pip setuptools wheel && \
    /opt/venv/bin/pip install \
        # wheel \
        python-can==4.6.1 \
        influxdb==5.3.2 \
        pyserial \
        paho-mqtt==2.1.0 \
        pika==1.3.2 \
        requests==2.32.5 \
        urllib3==2.5.0

# Ensure scripts inside the venv are runnable
ENV PATH="/opt/venv/bin:$PATH"

# install pyHPSU
RUN cd /opt \
    # && git clone --single-branch --branch Fix-unknown-mode https://github.com/Petrus79/pyHPSUmqtt.git pyHPSU\
    && git clone https://github.com/Petrus79/pyHPSUmqtt.git pyHPSU\
    && cd /opt/pyHPSU \
    && chmod +x install.sh \
    && sh install.sh

# Set PYTHONPATH so the HPSU module is discoverable
ENV PYTHONPATH="/opt/pyHPSU:$PYTHONPATH"

# expose volume
VOLUME /etc/pyHPSU

COPY entrypoint.sh /
RUN chmod +x entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
