FROM arm32v7/alpine:3.17

# build ARM on AMD64
COPY qemu-arm-static /usr/bin

# set variables and locales
ENV \
    LANG="C.UTF-8"

# install packages
RUN apk add --no-cache
    ca-certificates \
    git \
    python3 \
    py3-pip
RUN ln -sf python3 /usr/bin/python  

RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade      
    python3-can \
    python3-influxdb \
    python3-serial \
    python3-mysqldb \
    python3-paho-mqtt \
    python3-pika \
    python3-requests \
    python3-urllib3 \

# install pyHPSU
RUN cd /opt \
    && git clone https://github.com/N3rdix/pyHPSUmqtt.git \
    && cd /opt/pyHPSU \
    && chmod +x install.sh \
    && sh install.sh

# expose volume
VOLUME /etc/pyHPSU

COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
